--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Teunboeke/spawnondefault
build-by-default: true
branches:
- main
projects:
  spawnondefault:
    path: ""
    icon: "20201026_175145-1.png"
...
