--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/davidlouis101/SpawnOnDefaultWorld-Fixed
build-by-default: true
branches:
- main
projects:
  SpawnOnDefaultWorld-Fixed:
    path: ""
    icon: 20201021_150143.png
...
