--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Teunboeke/spawnondefault-
build-by-default: true
branches:
- main
projects:
  spawnondefault-:
    path: ""
    icon: "Logo/20201021_150143.png"
...
